export const ATTRACTION_BY_SLUG_QUERY = `
  *[_type == "attraction" && slug.current == $slug][0]{
    _id,
    attractionId,
    name,
    slug,
    subRegionProvince,
    continentRegion,
    latitude,
    longitude,
    type,
    unescoStatus,
    heritageEra,
    suitableFor,
    difficultyAccessLevel,
    entryFeeInternational,
    entryFeeLocal,
    entryFeeDisplayText,
    bestTimeToVisit,
    timeNeeded,
    gettingThere,
    nearestAirportIATA,
    nearestAirportDistanceKm,
    primaryBrandPillar,
    secondaryPillar,
    experienceTags,
    metaTitle,
    metaDescription,
    focusKeyword,
    secondaryKeywords,
    editorialSummary,
    googleMapsPlaceId,
    addressDirections,
    contentStatus,
    lastVerifiedDate,
    articleBody,
    "country": country->{ name, "slug": slug.current },
    "city": city->{ name, "slug": slug.current },
    "nearbyCities": nearbyCities[]->{ name, "slug": slug.current },
  }
`

export const ALL_PUBLISHED_SLUGS_QUERY = `
  *[_type == "attraction" && contentStatus == "Published"]{ "slug": slug.current }
`
