import { defineField, defineType } from 'sanity'

const continentRegions = [
  { title: 'North Africa', value: 'North Africa' },
  { title: 'West Africa', value: 'West Africa' },
  { title: 'East Africa', value: 'East Africa' },
  { title: 'Southern Africa', value: 'Southern Africa' },
  { title: 'Central Africa', value: 'Central Africa' },
  { title: 'Indian Ocean Islands', value: 'Indian Ocean Islands' },
]

const attractionTypes = [
  'UNESCO World Heritage Site',
  'UNESCO World Heritage Site | National Park / Wildlife Reserve',
  'UNESCO World Heritage Site | Historical / Archaeological Site',
  'UNESCO World Heritage Site | Historic Medina',
  'UNESCO World Heritage Site | Rock Art Site',
  'UNESCO World Heritage Site | Living Historic City',
  'UNESCO World Heritage Site | Geological Site',
  'Roman Archaeological Site',
  'Medieval Islamic Archaeological Site',
  'Historical / Archaeological Site',
  'National Park / Wildlife Reserve',
  'Safari / Wildlife Experience',
  'Mountain / Highland',
  'Volcano / Geological',
  'Geothermal / Geological Site',
  'Beach / Coastal',
  'Desert / Oasis',
  'Wetland / Floodplain',
  'Lake / Waterway',
  'Island',
  'Rock Art Site',
  'Cave',
  'Forest / Rainforest',
  'City / Town / Neighbourhood',
  'Historic Medina',
  'Religious Site',
  'Museum / Memorial',
  'Market / Bazaar',
  'Cultural Experience',
  'Wine Tourism',
  'Scenic Route / Road Trip',
  'Resort / Theme Park',
  'Wildlife Sanctuary / Eco-site',
  'Diving / Marine',
].map(t => ({ title: t, value: t }))

const suitableForOptions = [
  'Solo Travelers',
  'Solo Travelers (with precautions)',
  'Couples',
  'Families',
  'Families (older children)',
  'Families (young children)',
  'Backpackers',
  'Hikers',
  'Photographers',
  'Nature Lovers',
  'History Enthusiasts',
  'Archaeology Buffs',
  'Educational Groups',
  'Luxury Travelers',
  'Adventure Seekers',
].map(t => ({ title: t, value: t }))

const brandPillars = [
  { title: 'Destinations', value: 'Destinations' },
  { title: 'Culture & Heritage', value: 'Culture & Heritage' },
  { title: 'Experiences', value: 'Experiences' },
  { title: 'African Food Tourism', value: 'African Food Tourism' },
  { title: 'Travel Planning', value: 'Travel Planning' },
]

const contentStatuses = [
  { title: 'Draft', value: 'Draft' },
  { title: 'Verified', value: 'Verified' },
  { title: 'Needs Update', value: 'Needs Update' },
  { title: 'Incomplete', value: 'Incomplete' },
  { title: 'Published', value: 'Published' },
  { title: 'Archived', value: 'Archived' },
]

export const attraction = defineType({
  name: 'attraction',
  title: 'Attraction',
  type: 'document',
  groups: [
    { name: 'record', title: 'Record ID' },
    { name: 'geographic', title: 'Geographic' },
    { name: 'profile', title: 'Profile' },
    { name: 'logistics', title: 'Logistics' },
    { name: 'taxonomy', title: 'Taxonomy' },
    { name: 'seo', title: 'SEO' },
    { name: 'geo', title: 'GEO' },
    { name: 'ops', title: 'Ops' },
    { name: 'content', title: 'Article Content' },
  ],
  fields: [
    // ─── RECORD ID ───────────────────────────────────────────────────────────
    defineField({
      name: 'attractionId',
      title: 'Attraction ID (Col 01)',
      type: 'string',
      group: 'record',
      description: 'Format: ATT-XXXX. Sequential, zero-padded. Never reuse.',
      validation: r => r.regex(/^ATT-\d{4}$/, { name: 'ATT-XXXX format' }),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug (Col 02)',
      type: 'slug',
      group: 'record',
      description: 'Pattern: {attraction-name}-{city}-{country}. Lowercase, hyphens only. Max 70 chars. Permanent once published.',
      options: { source: 'name' },
      validation: r => r.required(),
    }),

    // ─── GEOGRAPHIC ──────────────────────────────────────────────────────────
    defineField({
      name: 'name',
      title: 'Attraction Name (Col 03)',
      type: 'string',
      group: 'geographic',
      description: 'Official English name. No trailing punctuation.',
      validation: r => r.required(),
    }),
    defineField({
      name: 'country',
      title: 'Country (Col 04)',
      type: 'reference',
      to: [{ type: 'country' }],
      group: 'geographic',
      validation: r => r.required(),
    }),
    defineField({
      name: 'subRegionProvince',
      title: 'Sub-Region / Province (Col 05)',
      type: 'string',
      group: 'geographic',
      description: 'Official administrative division name.',
    }),
    defineField({
      name: 'city',
      title: 'City (Col 06)',
      type: 'reference',
      to: [{ type: 'city' }],
      group: 'geographic',
      description: 'Nearest city of meaningful size. Never a village or suburb.',
    }),
    defineField({
      name: 'nearbyCities',
      title: 'Nearby Cities (Col 07)',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'city' }] }],
      group: 'geographic',
      description: 'Day-trip distance cities only.',
    }),
    defineField({
      name: 'continentRegion',
      title: 'Continent Region (Col 08)',
      type: 'string',
      group: 'geographic',
      options: { list: continentRegions },
      validation: r => r.required(),
    }),
    defineField({
      name: 'latitude',
      title: 'Latitude (Col 09)',
      type: 'number',
      group: 'geographic',
      description: '6 decimal places. Visitor entry point. Source: Google Maps.',
    }),
    defineField({
      name: 'longitude',
      title: 'Longitude (Col 10)',
      type: 'number',
      group: 'geographic',
      description: '6 decimal places. Same source and precision as Latitude.',
    }),

    // ─── PROFILE ─────────────────────────────────────────────────────────────
    defineField({
      name: 'type',
      title: 'Attraction Type (Col 11)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'profile',
      options: { list: attractionTypes },
      validation: r => r.required().min(1),
    }),
    defineField({
      name: 'unescoStatus',
      title: 'UNESCO Status (Col 12)',
      type: 'string',
      group: 'profile',
      description: 'Full designation name + inscription year. Verify at whc.unesco.org. Leave blank if not a UNESCO site.',
    }),
    defineField({
      name: 'heritageEra',
      title: 'Heritage Era (Col 13)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'profile',
      description: 'e.g. Colonial Era, Roman Imperial, 20th Century',
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'suitableFor',
      title: 'Suitable For (Col 14)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'profile',
      options: { list: suitableForOptions },
    }),
    defineField({
      name: 'difficultyAccessLevel',
      title: 'Difficulty / Access Level (Col 15)',
      type: 'string',
      group: 'profile',
      options: {
        list: [
          { title: 'Easy', value: 'Easy' },
          { title: 'Moderate', value: 'Moderate' },
          { title: 'Strenuous', value: 'Strenuous' },
          { title: 'Guided Tour Recommended', value: 'Guided Tour Recommended' },
        ],
      },
    }),

    // ─── LOGISTICS ───────────────────────────────────────────────────────────
    defineField({
      name: 'entryFeeInternational',
      title: 'Entry Fee — International USD (Col 16)',
      type: 'number',
      group: 'logistics',
      description: 'USD equivalent, numeric only. e.g. 22',
    }),
    defineField({
      name: 'entryFeeLocal',
      title: 'Entry Fee — Local / Resident USD (Col 17)',
      type: 'number',
      group: 'logistics',
      description: 'USD equivalent, numeric only.',
    }),
    defineField({
      name: 'entryFeeDisplayText',
      title: 'Entry Fee Display Text (Col 18)',
      type: 'text',
      rows: 3,
      group: 'logistics',
      description: 'Full tier breakdown in local currency. Include [VERIFY] and source URL.',
    }),
    defineField({
      name: 'bestTimeToVisit',
      title: 'Best Time to Visit (Col 19)',
      type: 'text',
      rows: 3,
      group: 'logistics',
      description: 'Ranked preference order. Not just a date range.',
    }),
    defineField({
      name: 'timeNeeded',
      title: 'Time Needed in Hours (Col 20)',
      type: 'number',
      group: 'logistics',
      description: 'Minimum practical visit in hours. Numeric.',
    }),
    defineField({
      name: 'gettingThere',
      title: 'Getting There (Col 21)',
      type: 'text',
      rows: 4,
      group: 'logistics',
      description: 'Full practical directions. Costs in local currency with year.',
    }),
    defineField({
      name: 'nearestAirportIATA',
      title: 'Nearest Airport IATA Code (Col 22)',
      type: 'string',
      group: 'logistics',
      description: '3-letter IATA code only. Verify at iata.org.',
      validation: r => r.max(3).uppercase(),
    }),
    defineField({
      name: 'nearestAirportDistanceKm',
      title: 'Nearest Airport Distance km (Col 23)',
      type: 'number',
      group: 'logistics',
      description: 'Driving distance. Google Maps. Not straight-line.',
    }),

    // ─── TAXONOMY ────────────────────────────────────────────────────────────
    defineField({
      name: 'primaryBrandPillar',
      title: 'Primary Brand Pillar (Col 24)',
      type: 'string',
      group: 'taxonomy',
      options: { list: brandPillars },
      validation: r => r.required(),
    }),
    defineField({
      name: 'secondaryPillar',
      title: 'Secondary Pillar (Col 25)',
      type: 'string',
      group: 'taxonomy',
      options: { list: brandPillars },
    }),
    defineField({
      name: 'experienceTags',
      title: 'Experience Tags (Col 26)',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'taxonomy',
      description: 'Specific tags for faceted search and internal linking.',
      options: { layout: 'tags' },
    }),

    // ─── SEO ─────────────────────────────────────────────────────────────────
    defineField({
      name: 'metaTitle',
      title: 'Meta Title (Col 27)',
      type: 'string',
      group: 'seo',
      description: 'Target 55-60 chars. Focus keyword leads. No brand name at start.',
      validation: r => r.max(65),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description (Col 28)',
      type: 'text',
      rows: 3,
      group: 'seo',
      description: 'Target 145-155 chars. Not same as Editorial Summary.',
      validation: r => r.max(160),
    }),
    defineField({
      name: 'focusKeyword',
      title: 'Focus Keyword (Col 29)',
      type: 'string',
      group: 'seo',
      description: '2-4 words. ONE per page. Must appear in H1, first 100 words, Meta Title, Meta Description, URL slug.',
    }),
    defineField({
      name: 'secondaryKeywords',
      title: 'Secondary Keywords (Col 30)',
      type: 'text',
      rows: 4,
      group: 'seo',
      description: '5-12 pipe-separated phrases. Map each to a FAQ question.',
    }),
    defineField({
      name: 'editorialSummary',
      title: 'Editorial Summary (Col 31)',
      type: 'text',
      rows: 3,
      group: 'seo',
      description: '2-3 sentences. Used on listing cards and Article schema. Focus keyword in sentence 1.',
    }),

    // ─── GEO ─────────────────────────────────────────────────────────────────
    defineField({
      name: 'googleMapsPlaceId',
      title: 'Google Maps Place ID (Col 32)',
      type: 'string',
      group: 'geo',
      description: 'Starts with ChIJ. Retrieve from Google Maps. Verify before each publish batch.',
    }),
    defineField({
      name: 'addressDirections',
      title: 'Address / Directions (Col 33)',
      type: 'text',
      rows: 3,
      group: 'geo',
      description: 'Full postal address of visitor entry point: Street, Suburb, City, Province, Postal Code, Country.',
    }),

    // ─── OPS ─────────────────────────────────────────────────────────────────
    defineField({
      name: 'contentStatus',
      title: 'Content Status (Col 34)',
      type: 'string',
      group: 'ops',
      options: { list: contentStatuses },
      initialValue: 'Draft',
      validation: r => r.required(),
    }),
    defineField({
      name: 'lastVerifiedDate',
      title: 'Last Verified Date (Col 35)',
      type: 'date',
      group: 'ops',
      description: 'ISO 8601: YYYY-MM-DD.',
    }),
    defineField({
      name: 'sourceFile',
      title: 'Source File (Col 36)',
      type: 'string',
      group: 'ops',
      description: 'Exact filename of source .docx document.',
    }),

    // ─── ARTICLE CONTENT ─────────────────────────────────────────────────────
    defineField({
      name: 'articleBody',
      title: 'Article Body',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'content',
      description: 'The full 13-section article content.',
    }),
  ],

  preview: {
    select: {
      title: 'name',
      subtitle: 'contentStatus',
      media: 'heroImage',
    },
    prepare({ title, subtitle }) {
      return {
        title: title || 'Untitled Attraction',
        subtitle: subtitle ? `Status: ${subtitle}` : 'Status: Draft',
      }
    },
  },
})
