import { defineField, defineType } from 'sanity'

export const country = defineType({
  name: 'country',
  title: 'Country',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Country Name',
      type: 'string',
      description: 'Official English country name. Matches ISO 3166-1.',
      validation: r => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: { source: 'name' },
      validation: r => r.required(),
    }),
    defineField({
      name: 'continentRegion',
      title: 'Continent Region',
      type: 'string',
      options: {
        list: [
          { title: 'North Africa', value: 'North Africa' },
          { title: 'West Africa', value: 'West Africa' },
          { title: 'East Africa', value: 'East Africa' },
          { title: 'Southern Africa', value: 'Southern Africa' },
          { title: 'Central Africa', value: 'Central Africa' },
          { title: 'Indian Ocean Islands', value: 'Indian Ocean Islands' },
        ],
      },
      validation: r => r.required(),
    }),
    defineField({
      name: 'countryCode',
      title: 'ISO Country Code',
      type: 'string',
      description: '2-letter ISO 3166-1 alpha-2 code, lowercase (e.g. "ng" for Nigeria). Drives the real flag graphic — replaces flagEmoji, which renders inconsistently across devices and cannot be styled (WDOS I-01/X-02).',
      validation: r => r.length(2).lowercase(),
    }),
    defineField({
      name: 'overview',
      title: 'Country Overview',
      type: 'text',
      rows: 4,
      description: 'Short overview paragraph shown on the country hub page.',
    }),
    defineField({
      name: 'whenToGo',
      title: 'When to Go',
      type: 'text',
      rows: 3,
      description: 'Best time to visit and why (dry season, migration, festival timing, etc). Ranked preference, not just a date range.',
    }),
    defineField({
      name: 'knownFor',
      title: 'What It Is Known For',
      type: 'text',
      rows: 3,
      description: 'The specific, real things this country is known for. Concrete, not a generic "breathtaking" claim.',
    }),
    defineField({
      name: 'surprises',
      title: 'What Surprises People',
      type: 'text',
      rows: 3,
      description: 'What first-time visitors do not expect. Specific and true, not a marketing line.',
    }),
    defineField({
      name: 'gettingAround',
      title: 'Getting Around',
      type: 'text',
      rows: 3,
      description: 'Practical transport reality: domestic flights, road conditions, what visitors actually use to get between places.',
    }),
    defineField({
      name: 'visaInfo',
      title: 'Visa Position',
      type: 'text',
      rows: 4,
      description: 'Sourced from gov.uk or travel.state.gov only (Brain Layer 1.3). Must include [VERIFY] plus the source and the date it was checked — this changes, and a stale visa claim is worse than none.',
    }),
    defineField({
      name: 'safetyInfo',
      title: 'Safety Position',
      type: 'text',
      rows: 4,
      description: 'Sourced from gov.uk or travel.state.gov only (Brain Layer 1.3). Must include [VERIFY] plus the source and the date it was checked.',
    }),
    defineField({
      name: 'startHereAttractions',
      title: 'Start Here — 3 Attractions',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'attraction' }] }],
      validation: r => r.max(3),
      description: 'A curated pick of real, published attractions in this country — the "start here" set shown on the overview block. Never invent a placeholder reference; leave short if fewer than 3 published attractions exist yet.',
    }),
    defineField({
      name: 'quickFacts',
      title: 'Quick Facts',
      type: 'text',
      rows: 3,
      description: 'Capital, currency, language, visa info summary.',
    }),
    defineField({
      name: 'flagEmoji',
      title: 'Flag Emoji (deprecated)',
      type: 'string',
      description: 'Deprecated — use countryCode instead. No longer rendered anywhere on the site. Field kept only so existing values are not silently discarded.',
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'continentRegion' },
  },
})
