import { attraction } from './attraction'
import { country } from './country'
import { city } from './city'
import { editorialPillar } from './editorialPillar'
import { author } from './author'
import { savedAttraction } from './savedAttraction'
import { savedTrip } from './savedTrip'
import { comment } from './comment'
import { userRole } from './userRole'
import { post } from './post'
import { sourcedImage } from './sourcedImage'
import { event } from './event'
import { eventCollection } from './eventCollection'
import { magicLinkToken } from './magicLinkToken'

export const schemaTypes = [attraction, country, city, editorialPillar, author, savedAttraction, savedTrip, comment, userRole, post, sourcedImage, event, eventCollection, magicLinkToken]
